### ISSUE TITLE
as a city employee i want to be able to crop the picture i have uploaded

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/linkedevents-ui#111]
I want to be able to select which area of the uploaded picture I want to use as the cropped standard-sized picture for the event. 

![image](https://cloud.githubusercontent.com/assets/2391876/14012303/af6a4876-f1ad-11e5-8db1-6b3462b1aa7e.png)

**Comment by Rikuoja** [comment]
Duplicate of #142.
