### ISSUE TITLE
formatting does not look ok when viewing an existing event in the backend

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/linkedevents-ui#112]
the event description shows the html-formatting in the UI:

![image](https://cloud.githubusercontent.com/assets/2391876/14012377/0b94ff88-f1ae-11e5-951c-63cd27c6669e.png)

**Comment by Rikuoja** [comment]
Yeah, this depends on what will be our official recommendation on the linkedevents description data format.

If we want to accept HTML input in the form (as is currently present in Helmet events), then the form should generate HTML when necessary, and the preview should display it correctly.

**Comment by aleksisalonen** [comment]
Fixed.
