### ISSUE TITLE
"Validation errors" message persists and blocks submission despite clearing the offending field

### ISSUE THREAD

**Issue by hkotkanen** [City-of-Helsinki/linkedevents-ui#113]
Reported by a user, should invesrigate and try to reproduce. Offending field was a malformed url in offers.info_url.

**Comment by Rikuoja** [comment]
Rereported by another user. Offending field was missing location.

**Comment by jussiarpalahti** [comment]
Not able to reproduce, tested with Chrome, IE11 and IE10.

**Comment by Rikuoja** [comment]
Rereported yet again. ” Yritän tehdä muutoksia Sauvakävely-tapahtumaan, mutta tulee ilmoitus ”Lomakkeessa on virheistä. Tarkista lomake.” Kaikki tarvittavat kohdat on kuitenkin täytetty. Mistä johtuu että muutos ei tallennu?”

**Comment by Rikuoja** [comment]
`
{"name":{"fi":"Marttatapagttuma"},"event_status":"EventScheduled","publication_status":"public","location":{"name":{"fi":"Asuntosäätiön Asumisoikeus Oy/Markkulantie 27"},"id":"tprek:37562","@id":"/v1/place/tprek:37562/"},"keywords":[{"@id":"https://api.hel.fi/linkedevents-test/v1/keyword/helfi%3A10/"}],"external_links":[],"start_time":"2016-12-31T22:00:00.000Z"}`

cannot be posted as Location does not exist in LE.

**Comment by Rikuoja** [comment]
Any recent info on the bug?

**Comment by aleksisalonen** [comment]
Fixed again in https://github.com/City-of-Helsinki/linkedevents-ui/issues/298
