### ISSUE TITLE
"Helsinki" no longer found in the places autocomplete list

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#114]
Update instructions for adding a custom place, or allow adding a custom place. Current instructions are to use "Helsinki" for events that take place outside tprek locations.

**Comment by Rikuoja** [comment]
This is due to us using servicemap API for autocomplete. Requires a Design Decision.

**Comment by tituomin** [comment]
Uneventfuk places added to linkedevents api search endpoint. Next: make ui use it.

**Comment by Rikuoja** [comment]
Hm, couldn't find the commit for the backend?
