### ISSUE TITLE
Only 100 most recently edited events are listed

### ISSUE THREAD

**Issue by juyrjola** [City-of-Helsinki/linkedevents-ui#127]
Should be paged or infinity scrolled. Also applies for search results.

**Comment by Rikuoja** [comment]
Also, display a load indicator while doing the search, and display "No events found" or the like if zero results were returned.

**Comment by aleksisalonen** [comment]
Will be fixed in #191 for Event management -view. This issue now only applies to search ressults -view.

**Comment by aleksisalonen** [comment]
Done.
