### ISSUE TITLE
Separate image bank and individual image operations into tabs in the modal

### ISSUE THREAD

**Issue by hkotkanen** [City-of-Helsinki/linkedevents-ui#146]
First tab "Image bank" lets the user choose an existing image or upload a new one. The second tab "Chosen image" lets the user view and modify metadata associated with the image (photographer, cropping, license etc)

**Comment by hkotkanen** [comment]
relevant issues: #145, #140, #141, #142

**Comment by Rikuoja** [comment]
Implemented in a modal, not in a tab.
