### ISSUE TITLE
Add BIG banner to indicate test environment (and preferably deployed commit hash) into index.jade file

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#151]
This is to inform user that they have entered a test instance, not a production instance. Also will allow us to check which commit is deployed where.

**Comment by jussiarpalahti** [comment]
Possible easiest route is to use build env variable test for other than production modes. Index.jade generates static index.html which can in dev mode display something suitably noticeable.

Commit hash thing works purportedly like this https://github.com/City-of-Helsinki/helerm-ui/pull/1

**Comment by jussiarpalahti** [comment]
Is the commit hash to go in production view as well? @Rikuoja

**Comment by jussiarpalahti** [comment]
This is how it looks like now:
<img width="917" alt="kuva" src="https://cloud.githubusercontent.com/assets/11941245/21257338/53b35cf2-c380-11e6-8952-5406379145ef.png">

@Rikuoja care to give some feedback..? ;)

**Comment by Rikuoja** [comment]
@jussiarpalahti I would have the commit has somewhere rather hidden but still present in production. This could be a general component for all of our services.

Could the banner actually be rendered on top of the existing view, with explanation text (this is not the production instance) in Finnish, and a link to the production instance?

**Comment by jussiarpalahti** [comment]
The code doesn't actually know where its instances are, but I suppose this could be stated in an env variable.

Since commit hash is build time, static knowledge it can be easily written to the index.html (generated by index.jade). There's currently no common way to bring this information in all web apps...

I don't understand "on top of the existing view" part. It is on top of every view, since it's in the index.html before app's content div.

**Comment by Rikuoja** [comment]
Ah, by "on top" I meant in the z dimension. As in, a floating banner!

**Comment by jussiarpalahti** [comment]
But then it would block app's UI..?

**Comment by Rikuoja** [comment]
Yes, that's why the current implementation might be better! The current one changes the viewport size, but perhaps that's not a problem.

**Comment by jussiarpalahti** [comment]
Well, one could do make Github style banner (that diagonal "fork this on github" thing) and put that on the left corner, somewhat obscuring logo/app name. This won't change viewport size or anything.

**Comment by Rikuoja** [comment]
Would that be cool or what?

**Comment by jussiarpalahti** [comment]
Sigh.. At this stage I give up on the banner. I can't figure out why CSS I found doesn't work with what rest of the page is doing. This feature requires some design ❤️

I'll move on to commit hash thing.

**Comment by jussiarpalahti** [comment]
Commit Hash messaging now in its separate feature branch 2d03e9384325c84ac017b832ea042553bba0f55f
(no linking to branches so linked to its latest commit..)

Looking like this (that's browser's bottom right corner):
<img width="404" alt="nayttokuva 2016-12-27 kello 14 04 49" src="https://cloud.githubusercontent.com/assets/11941245/21499320/7c87939e-cc3d-11e6-8bbd-14dcbb6be174.png">

@Rikuoja

**Comment by jussiarpalahti** [comment]
Also, see c6a7be96eaf00a070abb0b18b3b1cd6422a1ad4b for testing banner

**Comment by Rikuoja** [comment]
Implemented!
