### ISSUE TITLE
Accept admin organizations array as User

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#156]
Display and allow editing events of all admin organizations. Requires backend issue linkedevents/#173

**Comment by aleksisalonen** [comment]
Is this something we need?

**Comment by Rikuoja** [comment]
This seems to be a duplicate of #284 .

Of course, what we will do with the user admin organization data is another thing (listing or not), but the UI needs to know which events the user has the right to modify.
