### ISSUE TITLE
Remove previously edited, unsaved event's contents from form

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/linkedevents-ui#158]
Steps to reproduce:

 * open existing event
 * **do not save it**
 * click "Lisää uusi tapahtuma"

Now form contents are set to previously opened event.

Fix: keep track of wether form is opened for editing or creating and what the previous state is. If changed, reset the contents.

**Comment by aleksisalonen** [comment]
No longer an issue, as the button is no longer displayed.
