### ISSUE TITLE
Add image metadata dialog to form

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#165]
User should be able to add following metadata for an image in UI: 1) name/description (corresponding "images" API field: "name"), 2) name of photographer ("photographer_name":) and 3) image license info ("license": "event_only" OR "cc_by").

When adding a new image to the API, user should be taken straight to corresponding Image info -dialog after image file is selected from computer. In browsing view, an icon for accessing the edit dialog of existing images should be displayed over the selected image. (see. Draft 1) Entire darkened band containing file name at bottom of image should be clickable for entry.

The edit dialog itself should contain fields for inputting name (160 char limit) and photographer name, and buttons for selecting either Creative Commons BY 4.0 ("cc_by") or Use with event only ("event_only") license. License selection is mandatory and mutually exclusive. CC is selected by default.

Draft for browsing view, image selected:

![image-adding-1](https://cloud.githubusercontent.com/assets/16101544/22244787/9a7f39d4-e235-11e6-8989-beab4ac9d083.jpg)

Icon used: https://material.io/icons/#ic_build

Draft for editing dialog:

![image-adding-2](https://cloud.githubusercontent.com/assets/16101544/22244801/a2fc911a-e235-11e6-9317-9d8578a88717.jpg)

**Comment by kallemakynen** [comment]
Should the edit window pop up also when uploading an external image? (The original description only says image files selected from computer)

**Comment by Rikuoja** [comment]
Yes, I think we will have to display the window at any case. External images might also have different licenses and metadata that needs to be added.
