### ISSUE TITLE
Add tool for copying Location ID and Keyword ID to clipboard

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#188]
Add (small grey) button under location and keyword fields which adds location ID and keyword ID  respectively for selected location / keword(s) to the users' clipboard.

**Comment by Rikuoja** [comment]
Location ID: Fix the field to allow copying to clipboard on IE/Firefox, or add button that copies the ID.
Keyword ID: Add button that copies all the selected IDs, comma-separated.
