### ISSUE TITLE
Allow manual sorting in Tapahtumien hallinta

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#191]
Allow user to sort events in Tapahtumien hallinta view according to event heading, start date, end date and last modified date.

Standard sorting functionality: clicking on any given sort condition sorts events accordingly and adds a ▼-symbol next to its name. A second click on the same condition will sort the events in reverse order and add a ▲-symbol. 

▼-symbol should be displayed by default next to the Modified last -column heading.

**Comment by Rikuoja** [comment]
Should be implemented using API `sort` parameter.

**Comment by Rikuoja** [comment]
Includes pagination, if not currently implemented in UI.

**Comment by aleksisalonen** [comment]
Addition:
**Group subevents under superevents in Tapahtumien hallinta**

Subevents and superevents should be grouped together. Display all subevents under their corresponding superevent. 

Superevents should be graphically distinguishable (i.e. bold) from subevents and subevents should be marked with an indentation vis-à-vis the superevent.
