### ISSUE TITLE
Remove occasional viewport jump when saving event

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#204]
On some occasions the UI viewport jumps upwards a few hundred pixels after the Save event-button is clicked. This behaviour should be removed.

**Comment by Rikuoja** [comment]
Only reproducible on Firefox?

**Comment by aleksisalonen** [comment]
Reproduced on IE11 and FF55, but not on Chrome.

**Comment by tkivela** [comment]
Tested with Firefox 52.5 but could not reproduce. After saving event there comes "julkaistun tapahtuman tallennus onnistui" notification, is viewport off at this stage or somewhere else? Could you perhaps attach a screenshot?

**Comment by aleksisalonen** [comment]
So far I'm not able to reproduce it myself anymore. Maybe the webpack and react version upgrades have worked their magic. Let's close this for now.
