### ISSUE TITLE
Enable attaching events to superevents in UI

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#205]
Users should be able to create  umbrella-type superevents and attach events to umbrella-type superevents though the UI. API has support for superevent–subevent-structure and the new super_event type "umbrella" that is pertitent here.

See: https://github.com/City-of-Helsinki/linkedevents/issues/299

The feature is designed for e.g. festivals which have several subevents, including subevents that are themselves series' and thus superevents.

*********

At the end of the event submission form add a new sub-heading "Kattotapahtumat" / Umbrella events.

Under it add the unchecked selections:
"■ Tämä tapahtuma on kattotapahtuma." / "This event is an umbrella event"
"■ Tällä tapahtumalla on kattotapahtuma." / "This event has an umbrella event."

When the second selection is checked, a search input field will be shown under it, with the ability to search the API for all umbrella-type events. The selection of the second will automatically disable the first selection (greying it out for the uset).
→ On hover of the greyed out element, display the text: "Alatapahtuma ei voi olla kattotapahtuma. A sub event cannot be an umbrella event."

When the first selection is checked, the second selection should be disabled (greyed out).
→ On hover of the greyed out element, display the text: "Kattotapahtumalla ei voi olla kattotapahtumaa. / An umbrella event cannot have an umbrella event."

**Rules and spesifics for creation**

The hierarchies that should be allowed here are :
• umbrella → recurring (→ subevent) 
• umbrella → subevent

This means that for individual subevents and existing umbrella-events the first checkbox should never be available (greyed out). For individual subevents, a text disclaimer should state:

"Jos haluat lisätä tämän tapahtuman osaksi kattotapahtumaa, tee se [link to new tab] sarjan ylätapahtumasta[/link to new tab]." / "If you wish to add this event under an umbrella event, you may do so from the associated [link to new tab]]top level event[/link to new tab]]."

The first checkbox should always be disabled (greyed out) as well for all existing recurring events AND for unsaved form content with more than one date.
→On hover of the greyed out element, display the text: "Tapahtumasarja ei voi olla kattotapahtuma / An event series cannot be an umbrella event."

**Search-element**

At the initial state, before a search is made, a text under the search results should read: "Huom. Kattotapahtuma täytyy luoda ennen kuin voit lisätä sille alatapahtumia." / NB. 
"An umbrella event has to be created before events can be added under it."

Search results should be displayed as a dropdown suggestion menu in the same style as existing search elements in the form (place, keywords).

**Editability after saving**

* An existing umbrella-status should be editable only if the event has no existing subevents.
* An existing "part of umbrella event"-status should always be editable.

**Comment by Rikuoja** [comment]
Prevent in the UI the possibility to add a subevent to an event which has a superevent, to prevent multi-tiered hierarchies. The API will accept adding a subevent to any event.

**Comment by Rikuoja** [comment]
Okay, apparently hierarchy umbrella <- recurring <- subevent should be allowed, but other three-tiered hierarchies should not be allowed? so only allow umbrella <- subevent, recurring <- subevent and umbrella <- recurring <- subevent.

**Comment by Rikuoja** [comment]
Currently there is no limitation on the API side on the complexity of event hierarchy, so I'm not sure if the limitation should concern the API or not.

**Comment by Rikuoja** [comment]
Also, I don't understand 
>When unchecked, a search input field will be shown, with the ability to search the API for all events (except) non-recurring-type superevents.

Surely, you mean that the user could select among all events except recurring-type superevents?

**Comment by aleksisalonen** [comment]
Quite right, I think I had to quit while in the middle of writing and ended up with that double-negative fumble.

**Comment by Rikuoja** [comment]
Okay :) Then, the next question is how do we display that the event has a recurring type superevent? 

Then, the form should display that there is already a superevent, but changing it should not be allowed, because the event belongs to a `recurring` superevent, and we don't want those to be changed manually?

**Comment by Rikuoja** [comment]
And if the user wants to make a recurring event part of an umbrella event, should we have a text that this event is a repeating event and the user should go to the superevent to attach the recurring superevent under the umbrella event?

**Comment by aleksisalonen** [comment]
Yes, no changing allowed for subevents of recurring events.

I think it should be displayed as a greyed out text, with a link to the superevent, under the same heading.

Ans yes we should probably inform the user of the chance to link the recurring superevent in the info box.

**Comment by aleksisalonen** [comment]
Of course, the initial search should not return existing subevents either, because that would result in more levels of hierarchy than we currently want.
