### ISSUE TITLE
Notify user when browsing the event submission form while not logged in

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#210]
The "Lisää uusi tapahtuma" tab can be accessed while not logged in. If browsing the submission form, user should be informed with a persistent message that submission is possible only when logged in.

The publish-button should also be disabled.

Message to be displayed:
"Jos haluat julkaista tapahtuman, kirjaudu ensin sisään."

**Comment by Rikuoja** [comment]
Should it? I thought so first, but it is actually quite nice for users to be able to check how the app is used even before they have the right to submit data.

Especially since failing to log in doesn't destroy the data, so no data is lost if you fill in the form before logging in.

**Comment by Rikuoja** [comment]
Perhaps add a notification on top of the form, and disable the Publish event button at the bottom with explanation that the user must be logged in before sending data?

**Comment by aleksisalonen** [comment]
This comes from an actual user case, so **something** should be done. Also, I should add, it would still be possible to look at the form without any submitting rights, because logging in is always allowed, while rights are managed.

Still, a persistent notification bar and disabling the publish-button should be enough. I'll modify the issue.

**Comment by aleksisalonen** [comment]
duplicate of #359
