### ISSUE TITLE
Sentry User Feedback integration

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/linkedevents-ui#223]
Add support for using Sentry feedback form:
https://docs.sentry.io/clients/javascript/usage/#javascript-user-feedback

Investigate wether form is customizable for finnish and LE's domain

There's an API as well
https://docs.sentry.io/api/projects/post-project-user-reports/

**Comment by jussiarpalahti** [comment]
Also, see #224 for Redux middleware support

**Comment by jussiarpalahti** [comment]
New Sentry SDK's guide: https://docs.sentry.io/learn/user-feedback/?platform=browser

**Comment by vikoivun** [comment]
So the basic problem is that currently our the feedback thingy gives us a blob of json in Sentry interface. We would like to make us the interfaces linked above to give us an easier to read reports in the interface. Especially separating using the form linked above will help.

It would also be nice if application state itself (everything but the "debug_message" and "commit_hash") could be pretty printed in sentry interface. I don't know if this is possible, but it bears looking into.

**Comment by aleksisalonen** [comment]
Ok for now (?)
