### ISSUE TITLE
Integrate Sentry Redux middleware and error reporting

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/linkedevents-ui#224]
Add Sentry integration with Redux state support:
https://github.com/ngokevin/redux-raven-middleware
https://blog.sentry.io/2016/08/24/redux-middleware-error-logging.html

Use case is to collect user's actions and Redux state tree when either errors happen or report is sent.

**Comment by jussiarpalahti** [comment]
Also, raven should be updated to newest version.

**Comment by jussiarpalahti** [comment]
https://docs.sentry.io/platforms/javascript/react/ Sentry has new SDK and Raven is deprecated.

**Comment by Rikuoja** [comment]
So, we may either update the dependencies or move to Sentry SDK instead, depending on which seems easier.

**Comment by aleksisalonen** [comment]
Ok for now (?)
