### ISSUE TITLE
Disable edit button for events in the past

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#232]
Yields weird errors when trying to PUT a past event and shouldn't be allowed anyway.

**Comment by aleksisalonen** [comment]
Past *events* I assume?

**Comment by Rikuoja** [comment]
Ahah! This is indeed not kerrokantasi.

**Comment by aleksisalonen** [comment]
Disable button and show tooltip on hover.

Tooltip text: "Menneisyydessä olevia tapahtumia ei voi muokata."
