### ISSUE TITLE
Add restrictions for image size

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#234]
Currently the user sees only the obscure "Virhe kuvaa luotaessa"

**Comment by Rikuoja** [comment]
413 Request Entity Too Large means we should display "Kuva on liian suuri! Jotta rajapinnan käyttäjät saisivat kuvat näkyviin nopeasti kaikilla laitteilla, kuvan koon on oltava alle 1 Mt."

**Comment by aleksisalonen** [comment]
Use error message:

Kuva on liian suuri. Kuvan koon on oltava alle 1 Mt.

**Comment by tkivela** [comment]
The error handling should be done to src/actions/userImages.js, from row #101 onwards. For some reason I could not get the error code in the fail function. Error description also just said "error". Also tried to configure statusCode -handler to jQuery, but for some reason the defined errorcode handler is never called.

Browser console reports: Failed to load https://api.hel.fi/linkedevents-test/v1/image/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 413.

**Comment by aleksisalonen** [comment]
New definition: Add an image size restriction: 2 Mb and user info messages.

"Kuva on liian suuri. Kuvan koon on oltava alle 2 Mt."

**Comment by aleksisalonen** [comment]
Ready.
