### ISSUE TITLE
Offers: Require only Price when is_free is false

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#236]
Currently when" offers" → "is_free": false, all of the following values are required in the form:

"description"
"info_url"
"price"

This should be changed, so that only the "price" value is required (and the rest are voluntary).

**Comment by aleksisalonen** [comment]
Also, when validating an existing event that is being modified, the form currently requires price info, even when the event is marked as free. This bug makes it impossible to modify free events.

**Comment by vikoivun** [comment]
Appears to be a bug with introduced with event deletion. I've rolled event deletion back and now things more or less work.

**Comment by aleksisalonen** [comment]
Duplicate with #278 .
