### ISSUE TITLE
Allow URLs without http:// and display correct error message

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#239]

**Comment by Rikuoja** [comment]
Currently, trying to input an URL without http:// results in persistent error messages that are displayed in the wrong fields.

![image](https://user-images.githubusercontent.com/9367712/30026678-9d32390a-9186-11e7-8292-aa3998d51e9a.png)

**Comment by tkivela** [comment]
Seems that there are some inconstensies in the price information validations, noticed that the redux store state is not updated if there are validation errors. So when updating for example url in price section with invalid url, the invalid url is not notified to user at all and updating gives no error (and invalid value is lost). The same kind of problem existed with date/time components also. I'm going to fix this issue in this one too.
