### ISSUE TITLE
Add a moderation view and moderation features

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#242]
Add functionality and a view for moderating events submitted by regular users (the lower of two tiers' of user rights, with the higher being admin) and some additional moderation features. The API has support for events pending moderation and multi-tiered user rights.

**The moderation body should consist of:**
1. the main moderation view
2. additional moderation buttons in event preview (for events pending approval)
3. additional moderation buttons in event editing (for events pending approval)

The main view and affiliated features should only be shown to moderators (admin level rights), that are part of organizations that have regular-level-members. 

. For any given moderator the main view will only feature events submitted by so called affiliated organizations that are situated under that moderator's own organization. See API-issue and ask tech lead for details: https://github.com/City-of-Helsinki/linkedevents/issues/248

A chart of the three possible moderation points:

![moderation-3](https://user-images.githubusercontent.com/16101544/53899504-04430b80-4043-11e9-8372-29dc1622c950.png)

**The main moderation view**

The events shown in the main moderating view are of two primary types:
1. unpublished events (the events pending approval)
2. published events

The events featured here will consist only of events submitted by users belonging to affiliated organizations that are situated under the organization of the moderator in question. 

The view should consist of two main panels: Pending approval and Published. Both panels should show a maximum of ten events before adding a scroll bar. The basic format and functionality for displaying Event info should be taken from the Tapahtumien hallinta view.

The two panels have one diferrence in the information columns: 
• The pending approval panel features heading, publisher(+), date and last modified columns.
• The published panel features heading, publisher, date and approval time / moderator columns.

(+) The publisher-column should include a mailto-link that contains the email associated with the event. This can be done using the solution fom #433 (we'll use the same string here).

The mailto-event should contain the event's name and some additional parts as the mails header. Format: Tapahtumailmoituksesi "[Tapahtuman nimi]" vaatii toimenpiteitä – Helsingin kaupunki 

Additionally the pending approval panel has checkboxes for mass operations and buttons for deleting and publishing events straight from the panel. 

The UI should prompt user approval with a dialog for all deletions and mass publishings (publishing more than one event, for example a whole series at the same time). The basic format for the dialog should be the same one that is in use in the submission form.

![modeliittyma-perusnakyma](https://user-images.githubusercontent.com/16101544/30692611-e99128dc-9ed4-11e7-99fa-7cf4a33c06f0.png)

**Additional moderation buttons in event preview**

Clicking on an event in the modration view should take the user to the event preview. For events pending approval this should have the buttons for editing, deleting and publishing the event respectively. The buttons should be displayed both on the top and the bottom of the preview.

Use the existing button layout, but disable (grey out) the buttons for canceling and copying. Add the button for publishing (Julkaise / Publish) to the left of the editing button.

**Additional moderation buttons in event editing**

Events pending approval should have a button for returning to the moderation view without changes, deleting the event and publishing the event respectively.

"Palaa tekemättä muutoksia" / "Return without changes". Place it left of the Publish button.

**After publishing**

When the event is published or deleted, the user should be returned to main moderating view with the notice that the event has been published / deleted on the bottom pop-up bar.

**Comment by aleksisalonen** [comment]
Notes:
1) Skip separate Event published screen and move straight back to main view after operations.
2) Moderators should have access to an email address of pending event "publisher".

**Comment by Rikuoja** [comment]
Okay. So the moderation list requires two GETs from the API:

>The events shown in the main moderating view are of two primary types:
>
>unpublished events (the events pending approval) 

Fetched with `/v1/event/?admin_user=true&publication_status=draft`

>published events

Fetched with `/v1/event/?admin_user=true&publication_status=public&publisher=affiliated_id_1,affiliated_id_2`

where the UI has to figure out `affiliated_id_1` and `affiliated_id_2` with the following procedure: go through *all* user admin organizations with `/v1/organization/id` calls and select those which have the type `affiliated` :D

**Comment by aleksisalonen** [comment]
This is done!
