### ISSUE TITLE
Allow searching for events in a time range without search text

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#244]

**Comment by aleksisalonen** [comment]
Will be fixed in #174.

**Comment by Rikuoja** [comment]
@aleksisalonen Looks like this is not fixed. This is because the form doesn't send a search query at all when the text field is empty :D But it *could* do it!

**Comment by aleksisalonen** [comment]
Fixed, along with separate No headings -error.
