### ISSUE TITLE
Replace CoH main categories with YSO-set

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#245]
Use this set:

yso:p1235    elokuvat
yso:p1947    hyvinvointi
yso:p14004    keskustelu
yso:p11185    konsertit
yso:p360    kulttuuritapahtumat
yso:p2739    kuvataide
yso:p316    leikkiminen
yso:p916    liikunta
yso:p15875    luennot
yso:p1808    musiikki
yso:p5121    näyttelyt
yso:p2149    opastus
yso:p10727    osallistuminen
yso:p6062    pelit
yso:p3670    ruoka
yso:p1278    tanssi
yso:p2625    teatteritaide
yso:p19245    työpajat
yso:p2771    ulkoilu
yso:p965    urheilu

to replace th Hel.fi-pääkategoriat (helfi:topics ) set on the form. The new set will be available from the keywordsets-endpoint as helsinki:topics.

Rename the section to Pääkategoriat / Main categories.

**Points of note:**

* Swap order of Keywords-subsection and the newly headlined Main category-subsection
* Keywords-section should mirror selections from Main categories and vice versa
* Find out if keywords can easily be displayed under the input field, instead of inside the field.
* Make at least one selection in the Main category section mandatory.
* After the solution is ready, the UI should not post helfi:topics or helfi:audiences.

This issue is still missing new info texts.

**Comment by Rikuoja** [comment]
The mapping to the keywords already exists in https://github.com/City-of-Helsinki/linkedevents-ui/commit/2828601 .

So I assume this means that the UI should stop sending hel.fi keywords altogether, and only send the YSO keywords?

**Comment by Rikuoja** [comment]
Ah, so I guess we just need a similar mapping from main categories in the code, then we're all set.

Is there any timetable for when we can stop actually sending the hel.fi specific audiences and keywords?

**Comment by aleksisalonen** [comment]
Not at the moment. Is there a pressing reason to do so? 

The most important thing is to have all the category data available in YSO. It seems of only secondary inmportance that only YSO keywords are used, and that would include stripping kulke and helmet data of extraneous keywords as well.

**Comment by Rikuoja** [comment]
Nope, I'm just thinking the user of the UI; then the Helsinki keywords will automatically create certain YSO keywords might not be noticed by the user, and then they will add the same category again in the keywords field, or use a slightly different YSO keyword because they don't know hel.fi category already created some YSO keywords.

**Comment by Rikuoja** [comment]
Ah, but since this is the UI and not a backend issue, we can actually automatically add hel.fi categories in the form if the user selects the right YSO keywords, and add the YSO keywords if the user selects the hel.fi category :D Might still be confusing, though, for the user to have two elements (YSO and hel.fi) selecting essentially the same thing.

**Comment by aleksisalonen** [comment]
It's certainly not optimal. 

Some preselected obligatory keywords are still probably the next best thing to the mass training of users in the fine art of keywording.

My idea at current is to remove all the hel.fi keywords from the API in the long term, but still keep a separate section in the UI that features a small set of general YSO terms, in addition to the section that features target groups. That would at least clear things up a bit.

**Comment by Rikuoja** [comment]
Yeah, I agree that preselected categories that accidentally exactly correspond to YSO keyword mapping of hel.fi categories should be present. That way, we will get some categories fit for hel.fi, but I think it's better to just list them as the YSO keyword combinations they are.

This way, the user will understand that there is no need to pick the same YSO keyword again in the free keyword search field.

**Comment by Rikuoja** [comment]
Come to think of it, there just could be simple react magic that adds the checkboxed keywords to the object right away, which means the same keyword will be added to the YSO autocomplete list instantly. That way the user sees that the keyword is already present in the list. Similarly, remove the checkbox if the user deletes one of the keywords in the list. Could be tested if this will confuse the hell out of users or not.

**Comment by Rikuoja** [comment]
Let's call this set `helsinki:topics`, https://api.hel.fi/linkedevents/v1/keyword_set/helsinki:topics/ (does not exist yet).
