### ISSUE TITLE
Event ending time swallows validation errors silently

### ISSUE THREAD

**Issue by tkivela** [City-of-Helsinki/linkedevents-ui#255]
If event's end time is invalid then event saving informs no validation errors and event is saved without an ending time. 

If updating an existing event with an invalid ending time, saving does not inform of the error in the field and the old ending time (which was defined for the event before saving) stays.

Desired behaviour: User should be notified if there is an error on given end time and saving to backend should not be possible.

**Comment by tkivela** [comment]
Pushed a new commit which should fix this.

**Comment by aleksisalonen** [comment]
Fixed in test (but datepicker modal error will still stop most users from changing the wrong date.)

**Comment by aleksisalonen** [comment]
Was a bit too hasty: Error can still be reproduced, by entering a partial date, but that is very minor issue.
