### ISSUE TITLE
Delete event dialogue button is invisible

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#269]
Related to component updates. Apparently, some buttons are rendered invisible :( The button may (not) be seen in the form openede by clicking "Poista tapahtuma" on an existing event.

**Comment by tkivela** [comment]
Yes I noticed this too, and fixed it in development environment already. Commit to fix this is coming in issue #268 .

**Comment by tkivela** [comment]
This was solved in #268, closing now.
