### ISSUE TITLE
Change required Price-fields and clarify Price information-section

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#278]
This issue has four parts:

1) Change the required fields in the Price information-section ("Hintatiedot") so that only Price ("Hinta") will be set as mandatory.

2) Mark the Hinta-field with an asterisk to indicate compulsory nature.

3) Set the Hinta-field as the topmost field in its section.

3) Change the instruction-text to read:

"Merkitse onko tapahtuma maksuton. Syötä maksulliselle tapahtumalle hinta muodossa "5€".

Jos tapahtumalla on useita hintoja, klikkaa Lisää uusi hintatieto ja merkitse kunkin hintaryhmän nimi (esim. Lapset) Hintatietojen kuvaus -kenttään."

**Comment by Rikuoja** [comment]
I believe that while we are at it, we should verify that if we are copying an existing event, the price validation works as planned and does not crash, regardless of which fields are set. Currently I'm getting `ReferenceError: event is not defined` at https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/components/HelFormFields/MultiLanguageField.js#L59 when copying existing price data.

**Comment by tkivela** [comment]
@aleksisalonen about 4) : Is that the whole text or do we preserve the info about links in the instructions? Currently the text is (3 rows of text): 
Merkitse jos tapahtuma on maksuton tai lisää tapahtuman hinta tekstimuodossa (esim. 7€/5€).
Kerro mahdollisesta ennakkoilmoittautumisesta tai anna lisätietoja esimerkiksi paikkavarauksista.
Lisää mahdollinen linkki lipunmyyntiin tai ilmoittautumiseen.

**Comment by aleksisalonen** [comment]
Yes that's the whole of it. I think the field designator text is self-explanatory, no need to repeat it.
