### ISSUE TITLE
Trying to copy a cancelled event to create a new one fails

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#279]
This is because when copying, the event cancelled status remains. Therefore, if somebody accidentally cancels an event, they cannot create a new event from the copy.

**Comment by Rikuoja** [comment]
Related to issue https://github.com/City-of-Helsinki/linkedevents-ui/issues/311 . Essentially, we also need to remove the cancelled status, along with other validations that already exists.

**Comment by aleksisalonen** [comment]
Fixed.
