### ISSUE TITLE
Support admin_organizations and organization_memberships from backend user endpoint

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#284]
The backend currently uses `django-orghierarchy` which includes multiple `admin_organizations` and the possibility to have non-admin `organization_memberships` for a user. Therefore, we want to understand these new fields in the `user` endpoint.

**Comment by Rikuoja** [comment]
So, this means the UI knows which events the user may edit (admin), and which events the user may edit as a draft (member).

How we display the event list, then, is another issue. Do we display them all mixed in the event list on the main page?

This would mean the UI should display the user which organization is the publisher of each event.

**Comment by Rikuoja** [comment]
I believe the most elegant solution would be to add an API call `/v1/event/?user=user_uuid` ?

**Comment by Rikuoja** [comment]
Don't know if we want to have actually separate `/v1/event/?admin_user=uuid` and `/v1/event/?regular_user=uuid` calls?

Because we want to have two lists for events that the user can publish and events that the user can edit as draft?

**Comment by Rikuoja** [comment]
Okay. Currently no drafts, so we just need one call: `/v1/event/?admin_user=uuid` =)

**Comment by Rikuoja** [comment]
Okay, this listing issue is (partly) implemented already in https://github.com/City-of-Helsinki/linkedevents-ui/issues/358 .

**Comment by Rikuoja** [comment]
However, what remains to be done here are two things:

1) actually allow editing the events/drafts the user has rights to, defined by https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/utils/checkEventEditability.js

2) list only *published* events for admin users, but drafts *and* public events for regular users. So this means:

- if the user has *any* admin organizations, fetch event list with `/v1/event/?admin_user=true&publication_status=public`

-if the user has *only* regular organization, fetch event list `/v1/event/?regular_user=true` .

I will have to implement the latter filter in the backend.

**Comment by Rikuoja** [comment]
For the regular user, visually differentiate drafts and published events with the `draft` label (should already be present).

**Comment by aleksisalonen** [comment]
Will be finished under #242 and associated issues.
