### ISSUE TITLE
Changing a multi-lingual event's is_free-status disables saving

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#285]
If a user tries to change the is_free-status ("Maksuton") of an **existing** event, the form refuses to save the changes. This only occurs when the event in question has at least two input languages selected.

If changing from free to not free, form produces error message "Hintatietoja puuttuu." when trying to save.

If changing from not free to free, no error message is produced, but the event is not saved.

**Comment by Rikuoja** [comment]
In production, this shows up as issue https://sentry.hel.ninja/aok/linked-events-ui/issues/5735/?referrer=slack in sentry: 

```
ReferenceError
event is not defined
./components/HelFormFields/MultiLanguageField.js in _this2 at line 58:41
            if (this.props.setDirtyState) {
                this.props.setDirtyState()
            }
        }
        if(typeof this.props.onBlur === 'function') {
            this.props.onBlur(event, this.getValue())
        }
```

**Comment by aleksisalonen** [comment]
That does seem to be the case, as I'm unable to reproduce teh bug anymore on FF!
