### ISSUE TITLE
Social media url's cause form to crash

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#286]
![some-url-2](https://user-images.githubusercontent.com/16101544/35283589-53e7b3f2-0061-11e8-8674-ac339b86d31e.png)

Filling the url-fields in "Tapahtuma sosiaalisessa mediassa" will cause the form to crash, thus disabling the saving of an event.

**Comment by Rikuoja** [comment]
This is an API issue, since the new URL handler allows non-prefixed URLs not allowed by the API.

**Comment by Rikuoja** [comment]
Fixed by 30f5951
