### ISSUE TITLE
New event with price causes false price-error on Firefox

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#301]
Trying to create a new event with a price ('Hinta'-field) causes a price information missing-error when saving, even though the price is entered. Error appears to be browser-spesific to Firefox.

Reproducible on Firefox 55.0.3 (64-bit), but not on IE11 or various Chrome versions.

Related error: `ReferenceError: event is not defined`

**Comment by Rikuoja** [comment]
The error comes at https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/components/HelFormFields/MultiLanguageField.js#L59
