### ISSUE TITLE
Enable mass editing of published event series

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#313]
[Updated on 29.10.2019]

Mass creation of events in a single series (series = subEvents that have the same superEvent + superEvent) is currently possible, but mass editing is not.

Add a functionality that enables the user to mass edit all sub-events by editing the super-event. Data from the super-event should overwrite all applicable sub-event data (ie. not dates).

Upon saving, the user should be prompted: 

"Tiedot tallennetaan kaikkiin tapahtumiin tässä sarjassa. Aiemmat muutokset menetetään. Oletko varma että haluat jatkaa?" / "The changes will effect all events in the series. Any previous changes will be lost. Are you sure you want to continue?"

**Comment by aleksisalonen** [comment]
Issue should be solved only after:

https://github.com/City-of-Helsinki/linkedevents-ui/issues/259

**Comment by niglu1** [comment]
> Add a checkbox-based selection element for selecting the subevents whose data should be overridden.

To be able to do this we would need to refactor the whole confirmation dialog functionality that we have. At the moment it only supports displaying of some static HTML, which isn't enough for what the specs are asking for. Refactoring the confirmation dialog warrants it's own ticket as it's quite a lot of work.

What we can do though, is to show a confirmation dialog with the message described in the ticket and then listing all the sub events that would be affected. But then again, that would always save all the changes to the super event to the sub events as well and that might not always be desirable?
