### ISSUE TITLE
UI produces false 404-responses

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#315]
UI doesn't allow direct links to subpages, ie. https://linkedevents.hel.fi/search or https://linkedevents.hel.fi/event/kulke:44677.

Addresses produce a 404-response. Direct links should be allowed. A 404 response is also false.

Current behaviour has been introduced in an update most likely after Q3 / 2017.

**Comment by Rikuoja** [comment]
This is exceedingly weird, since the router itself does use those addresses when navigated to by clicking links within the app. :(

**Comment by vikoivun** [comment]
All right. So it is not an obvious deployment bug. Instead it is an obscure bug with the "production"-server within server/server.js. Should I try to fix that, or instead just configure nginx to handle everything but /auth?

**Comment by aleksisalonen** [comment]
Fixed.
