### ISSUE TITLE
[Feature] Implement new UI changes to LinkedCourses

### ISSUE THREAD

**Issue by midori0507** [City-of-Helsinki/linkedevents-ui#325]
- [x] Create new branch `linked-courses` or similar from this repo `master` brach
- [ ] Keep `Link Courses`-related color and string/ config in separate file and constants. 
- [x] - Use Helsinki Grotesk everywhere 

- [ ] - Use font-awesome icons if needed (not other icons)

Navbar

- [x] - Make two storey as in hel-page-templates. First level new-style logo on the left edge, login on the right. Background $hel-tram
- [x] - Second level service name and navlinks on the left. “Add new course” button on the right
- [x] - Remove icons on navbar links

Content

- [x] - Use HelsinkiGrotesk in all text elements
- [x] - Make type color black
- [x] - Make input field bottomlines black (edited)

Bonus: 
- [x] use $hel-coat as a main color instead of $hel-tram

**Comment by Rikuoja** [comment]
I would suggest all the non-course specific things will also be made as a PR to the `master` branch. Only the course strings and the background color need be in a separate branch, so please put the course-specific things in a separate commit :) If you are improving the UX, Linkedevents can use most of it too.

**Comment by midori0507** [comment]
@Rikuoja Roger! I'll edit the description to fit the purpose

**Comment by Rikuoja** [comment]
Great, finally we will get up-to-date Helsinki looks to Linkedevents too :)

**Comment by Rikuoja** [comment]
I believe that to stay with the Helsinki spirit, hel-bus could be the color for Linkedevents-UI, while hel-tram is the color for Linkedcolors-UI.
