### ISSUE TITLE
Add new fields to editing UI

### ISSUE THREAD

**Issue by jimppa** [City-of-Helsinki/linkedevents-ui#326]
- provider_contact_info
- audience_max_age and audience_min_age
- offers_start_time and offers_end_time
- minimumAttendeeCapacity and maximumAttendeeCapacity

**Comment by aleksisalonen** [comment]
Related to Linked Courses -branch, not base LE.

**Comment by Rikuoja** [comment]
Well, rather, the fields are there already. Available with the `courses` setting. There is no separate Linked Courses branch.

**Comment by aleksisalonen** [comment]
Whatevs :P 

No, I knew I was unaware on how it's implemented.
