### ISSUE TITLE
Make SSO location configurable

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/linkedevents-ui#331]
https://github.com/City-of-Helsinki/linkedevents-ui/blob/3a043e0e4bf4852d898a2a117be4b8c73634a4b3/server/auth.js#L11 somewhere around here,

**Comment by midori0507** [comment]
@jussiarpalahti can you give more description: expected behaviors/current situation ?

**Comment by jussiarpalahti** [comment]
@Rikuoja Is this still relevant? Meaning, is SSO location hard-coded?

**Comment by Rikuoja** [comment]
At least this issue seems to indicate the location is hardcoded :D

**Comment by Rikuoja** [comment]
Yeah, this issue is outdated, what should be done is https://github.com/City-of-Helsinki/linkedevents-ui/issues/447
