### ISSUE TITLE
Sometimes HelDatePicker is given undefined defaultValue, resulting in TypeError

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#339]
We are getting
```
TypeError
 Määrittämättömän tai tyhjän viittauksen ominaisuutta _pf ei voi noutaa
```
in our production Sentry, which means sometimes `date` is undefined so `date._pf` fails at https://github.com/City-of-Helsinki/linkedevents-ui/blame/master/src/components/HelFormFields/HelDatePicker.js#L30 .

Couldn't reproduce locally, the reports are coming from IE11.

**Comment by midori0507** [comment]
Try to fix and evaluate in test server 
https://github.com/City-of-Helsinki/linkedevents-ui/commit/e53dad59d7838af8048c72862f63eb0ee8ccaa16

**Comment by midori0507** [comment]
Tested with IE11 on test server
