### ISSUE TITLE
Add delete image button to top of dialog and editing pop-up

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#353]
A) The delete button for deleting images in the images dialog should be added to the top portion of the dialog. 

If the organization has large numbers of images, the existing delete button is buried at the very bottom.

Place the new delete button at the bottom right corner of the top section.

B) Add a delete button to the image editing pop-up, as a wide button below the Tallenna tiedot button.

**Comment by jpnaveenkumar** [comment]
I wish to work on this

**Comment by Rikuoja** [comment]
@jpnaveenkumar Go ahead and give your suggestion!

**Comment by aleksisalonen** [comment]
Will be solved in #483
