### ISSUE TITLE
Allow additional event dates without end time

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#356]
Additional date fields don't allow dates without an ending datetime. Those should be allowed.

**Comment by dotanthanh** [comment]
This is not a matter of client validation, but rather related to the backend validation instead

**Comment by Rikuoja** [comment]
This is a backend issue, as the backend currently requires end times in all events. The UI doesn't require end time in any events, including additional ones.

**Comment by Rikuoja** [comment]
There doesn't seem to be a backend issue on the topic; we should discuss how to implement it there.

**Comment by Rikuoja** [comment]
Turns out this is a UI issue after all, related to https://github.com/City-of-Helsinki/linkedevents-ui/issues/357 and https://github.com/City-of-Helsinki/linkedevents-ui/issues/355 .

So somewhere in the form there are old end_times that are being POSTed if the user leaves the field empty.

**Comment by aleksisalonen** [comment]
Done.
