### ISSUE TITLE
Display all user editable events in Manage events-panel

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#358]
The Manage events-panel (Tapahtumien hallinta) should display all published events the user is allowed to edit. Currently only events submitted by one – even if the user belong to several – of the user's organizations are displayed.

The solution for fetching sub-organization events will be done from the backend side.

**Comment by Rikuoja** [comment]
Damn. Made the comments in the wrong issue: https://github.com/City-of-Helsinki/linkedevents-ui/issues/284

So, currently we don't display drafts, so we just need one call: /v1/event/?admin_user=uuid =) . That should (I'll implement the backend) list all events the user may edit.

**Comment by aleksisalonen** [comment]
Done.
