### ISSUE TITLE
Prevent events having identical start and end times

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#364]
The UI currently allows for events to have identical start and end times. Change the validation procedure so, that events should not be allowed to end at the same time as they start. (Ending in the past is already disallowed.)

**Comment by Rikuoja** [comment]
Then, we will have to specify the minimum length of an event. 1 second?

**Comment by aleksisalonen** [comment]
Sure, 1 second.
