### ISSUE TITLE
Add independent info text for cancel dialog

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#388]
The pop up dialogs for cancelling a super-event and a non-series event / subevent, should have a shared info text, that is independent of the delete-dialog.

The text for both cases of cancelling should read:

"Varmista tapahtuman peruminen

VAROITUS: Tämä toiminto peruuttaa tapahtuman lopullisesti. Tarvittaessa tapahtuman päivämäärää voi myös muuttaa."

The super-event delete-dialog *should not* include any mention of related subevents.

**Comment by Rikuoja** [comment]
Or would we rather just cancel the subevents instead, so we don't have to do this?

**Comment by aleksisalonen** [comment]
Well the texts would still be wrong, because they say the event is being deleted, which is not true.

**Comment by aleksisalonen** [comment]
Of course, if adding mass cancelling is easy, that should be done.

**Comment by aleksisalonen** [comment]
Solved in a separate issue.
