### ISSUE TITLE
Validate homepage-link

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#408]
Add validation for the homepage link. Allow only addresses starting with http:// or https://.

**Comment by niglu1** [comment]
@Rikuoja, @aleksisalonen is the task to show the validation message in a popup for the homepage field, similar to as it's shown for the SoMe links?

<img width="518" alt="Screenshot 2019-10-22 at 10 41 36" src="https://user-images.githubusercontent.com/12857859/67266398-db2f9800-f4b8-11e9-845d-6db3df78c4e0.png">
<img width="640" alt="Screenshot 2019-10-22 at 10 40 55" src="https://user-images.githubusercontent.com/12857859/67266399-db2f9800-f4b8-11e9-8c0c-3240edea434d.png">

**Comment by Rikuoja** [comment]
Yes, I believe the same URL validation can and should be used in both fields!

**Comment by Rikuoja** [comment]
Perhaps suggest https:// by default?

**Comment by Rikuoja** [comment]
Or will https suggestion confuse the user? Will they then not use the one that they have checked works? So many questions :P

**Comment by niglu1** [comment]
Could be useful, but yes, I'm pretty sure it could confuse some less tech savvy people

**Comment by aleksisalonen** [comment]
Yeah, use same solution as social media, don't suggest rhings :)

**Comment by aleksisalonen** [comment]
Yeah, use same solution as social media, don't suggest things :)

**Comment by aleksisalonen** [comment]
Let's amend the help text to:

Kirjoita osoite kokonaan ja muodossa http://... tai https://...

Enter the url in a correct format (http://... or https://...)
