### ISSUE TITLE
Cross-check first datetime with recurring tool start date

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#411]
If the datetime for the first date produced by the recurring event tool is the same as the one on the initial date inputted by the user in the regular form view, then that first date should not be reproduced by the tool.

If for example the user inputs 21.12. (a friday) on the initial date, then opens the recurring tool, and creates a series that starts on 21.12. and occurs on fridays, then the first date produced by the tool should be 28.12. for a one-week-interval, 04.12.2019 for a two-week.interval and so on, and not 21.12.

**Comment by Rikuoja** [comment]
Is this somehow related to https://github.com/City-of-Helsinki/linkedevents-ui/issues/195 ? Would seem that they are one and the same issue, i.e. that the first input date is also used in recurring events.
