### ISSUE TITLE
Append text about service centre card pertinently

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#412]
1) The text "Tapahtuma on tarkoitettu vain eläkeläisille ja työttömille, joilla on palvelukeskuskortti."

is appended to the description, when "Palvelukeskuskortti" is selected as a target group. If the event info is not supplied in Finnish, the text should not be added.

See for example:
https://linkedevents.hel.fi/event/helsinki:afubfo24yy

2) Add the appendage to English and Swedish descriptions when pertinent:

"The event is intended only for retired or unemployed persons with a Service Centre Card."

Link to anchor "Service Centre Card": https://www.hel.fi/sote/en/services/service-desription?id=3252

"Evenemanget är avsett endast för pensionärer eller arbetslösa med servicecentralkort."

Link to anchor "servicecentralkort": https://www.hel.fi/sote/sv/tjanster/tjanstebeskrivning?id=3252

**Comment by Rikuoja** [comment]
I believe the text should be added in the language the event info is instead? :D

**Comment by Rikuoja** [comment]
"Evenemanget är försett endast för pensionärer eller arbetslösa med servicecentralskort." or something along those lines?

**Comment by Rikuoja** [comment]
Probably försedd is the wrong verb here tho.

**Comment by Rikuoja** [comment]
Ah, "Evenemanget är avsett endast för pensionärer eller arbetslösa med servicecentralskort." must be the better translation.

**Comment by Rikuoja** [comment]
"The event is intended only for the retired and unemployed with a service centre card."

**Comment by Rikuoja** [comment]
Probably no need for Russian, Arabic and Chinese translations atm?

**Comment by Rikuoja** [comment]
Okay, added the respective links in the right languages, using the English link for Russian.

**Comment by Rikuoja** [comment]
Changed the "and" to "or" in Russian too.

**Comment by Rikuoja** [comment]
Just wanted to check with @genie9 that my Russian translation is correct =)
