### ISSUE TITLE
Allow for address-based locations

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#420]
Add the functionality for adding a location for an event that is not found in Toimipisterekisteri. The new location will be address-based.

The address data should be retrieved  from the Helsinki Region address dataset. Only addresses matching to the HRA-set will be accepted from the user input. Use a predictive input field where the address is selected by the user from the suggestions.

Display number of existing events at suggested addresses.

_Further spec and API-work needed_

**Comment by Rikuoja** [comment]
Place creation flow:

0) the user types the name or address to the location field. If a place with that name already exists, that one is used instead. (What if there is a location with that address that has the wrong name?)

1) the UI GETs the missing address-coordinate pair (as desired by the user) from the `/v1/address` endpoint, either with address OR with coordinate query string.

2) If the coordinates and the address are found, the UI will POST a place with those coordinates and address to the `/v1/place` endpoint. The name of the place should be "address, municipality" stringified. This place can then be used for further events in the same address.

**Comment by Rikuoja** [comment]
The problem with `Display number of existing events at suggested addresses.` is that in the first step, we are looking for existing places. If they have any number of events, they should not be allowed to be added again, as a place corresponding to that address has already been created.

So, in the dialogue where the user is creating a *new* address, only addresses that have *no* events may be found.

**Comment by Rikuoja** [comment]
Or, do we actually display the results for `/v1/place` and `/v1/address` search in the same search box?

With places first, and then matching addresses without a place (0 events) at the bottom? That way, the user would transparently either use an existing address or creating a new place with address, and wouldn't even know about it.

If that is the case, at which point do we create the new place? Before the event is created, to get its id? What if the user doesn't create an event in the end? That leaves us with a created place with zero events.

**Comment by aleksisalonen** [comment]
1) The user should not be made aware of the place–address divide. 

2) Displaying existing event numbers is not critically important.

3) Could we do all the matching at the send form data / save event -phase? If selected address matches existing place, don't create new place. If not, then do. (Or is that cumbersome?)

**Comment by Rikuoja** [comment]
1. Makes sense.

2. Can be done, since on the top of the list we will always display places with events. At the bottom, only display addresses with zero events.

3. Could be done. Then, of course, we cannot display the location id until it is created, and the event POSTing has one more step that can go wrong, if place creation does not succeed for some reason. This will have to be displayed to the user in some way.

Still, the question is, do we also check the addresses of existing named places? There might be several places with the same address already, the user might want to use one of them? That would mean on the list we fetch a) places according to their name *or* address field, and b) addresses.

**Comment by Rikuoja** [comment]
Another alternative would be to do everything in the backend, i.e. create all the places with addresses ready in the backend. This way, the UI wouldn't have to change at all, apart from checking place names *and* addresses in the search.

**Comment by aleksisalonen** [comment]
Nice idea. With the existing sorting done by popularity at the UI, addresses would probably not crowd out tprek-places.

The risk that comes to mind is that users will use addresses when a tprek-place is available, or that users will use addresses and places interchangeably.

Of course, creating places for every street **and** streetnumber will create a lot of places. Maybe that's not an issue.

**Comment by Rikuoja** [comment]
Yeah. The same risk, however, exists also when the addresses are created separately.

It is always possible that the user uses an address even though the location exists already.

**Comment by aleksisalonen** [comment]
Yes and no. I suppose we could have separate search fields in either case, with a user-initiated Place not found -selection in between.

**Comment by Rikuoja** [comment]
Yeah, we could always do that. If it feels like a good idea.

**Comment by aleksisalonen** [comment]
Well I think your idea is the simplest, so let's go with that.

The API-level solution can be thought of as a separate issue, if there's still need for the further functionalities later on.

**Comment by aleksisalonen** [comment]
Solved on the backend side (by importing address registry points as places in API).
