### ISSUE TITLE
Display event publisher in event preview

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#433]
Currently, the user has no way of knowing which organization has published the event they are watching, and why they are not allowed to edit the event.

Therefore, displaying event organizer in event preview (as well as in event editor) would make it easier for the user to contact the publisher regarding the event, if they have no admin rights themselves.

EDIT: Also show publishing organization in it's natural place among other public event data in the preview, under the Event Organizer.

**Comment by aleksisalonen** [comment]
![julkaisijatieto-2019](https://user-images.githubusercontent.com/16101544/66832643-00755100-ef63-11e9-92e6-685b71055b0d.jpg)


Info should displayed roughly as on this mockup.

Format:
Julkaisija: [Publisher name] / [User name]. [Publishing time]
Publisher:...

**Comment by Rikuoja** [comment]
Well, now the problem is that the API does not offer any user data to any users currently. The publisher is known, but not the user.

Surely we don't want to display user names to all users even outside the publisher organization?

**Comment by aleksisalonen** [comment]
I don't really see why the names of users should be hidden. In a case such as this, public sector workers' names are not considered private under GDPR. Although we should limit visibility to admin-level users, so this info will not become visible outside the city under normal circumstances even in the future.

We obviously don't want to make user names available from the API. If I remember correctly the data is easily available from the database.

**Comment by Rikuoja** [comment]
@aleksisalonen The UI uses the open API, just like all the other clients. Nobody has direct access to the database.

So, anybody could read all the user names from the API. That was exactly my point.

So, the question is, *how* do we limit the visibility of the user names in the API? Based on the user account? If a user logs in to the UI, will they be shown the user names instantly, or should they have some admin rights?

This means that e.g. external organization users that may be admin in some organization (not related to Helsinki) will see all the Helsinki event creator names? Your suggestion makes the names already visible outside the city.

**Comment by Rikuoja** [comment]
Once we know what are the circumstances exactly that we allow the API to show the user names, then I can make an API issue for this.

**Comment by aleksisalonen** [comment]
As I said, they should have admin rights. At current there are no external organizations, so the external visibily is not correct. However, it could become correct, so that bares taking into consideration.

If it's not too much of a hastle, I think a sufficient condition would be a) user is admin-user b) user is part of an ahjo-organization. If you think of a simpler way to separate internal and externla users, that's fine.

**Comment by Rikuoja** [comment]
There are already external organizations, ranging from Espoon kaupunki to Lippupiste. They just have no admins set yet.

**Comment by Rikuoja** [comment]
So, that would mean that any users within the *same* organization hierarchy would have access to the usernames. That could be a sensible first condition.

**Comment by aleksisalonen** [comment]
Well yes sure, one should be precise: there are no such organization-user-combos that would currently allow for the user names to be visible outside the city organization under the original conditions.

What hierarchy would an affiliated organization be a part of? Is it it's own hierarcy of one? If so, I guess that same hierarchy + some rights could work.

**Comment by aleksisalonen** [comment]
But that would probably leave out the case of affilaited org's. If they are considered part of the same hierarchy.

I don't think we want to give full view to affiliated org members.

**Comment by Rikuoja** [comment]
Yes, the affiliated ones kinda are within the same hierarchy, and kinda not. It's like a shadow hierarchy all of its own 👻

**Comment by Rikuoja** [comment]
Also, both organization types allow two tiers of members: admins and regular users (who can only post drafts). So we limit this to *admins* of *regular* organizations.

**Comment by aleksisalonen** [comment]
I think that should cover the actual cases.

Not the theoretical ones, though where for example non-existent normal Espoo admins gain horrifying access to the names of City of Helsinki employees' names.

Might be nice if affiliated folk could see each others' names within the same organization, but let's return to that if we ever get actual affiliated folk.

**Comment by Rikuoja** [comment]
One more thing: I guess this should work both ways, so that any admin in any organization lower in the hierarchy (such as a single unit) should also see the creator of all events from higher levels, such as city executive office, or any other department, and so on?

**Comment by Rikuoja** [comment]
> Not the theoretical ones though, where for example non-existent normal Espoo admins gain horrifying access to the names of City of Helsinki employees' names.

 Well, Espoo is not part of Helsinki at the moment, they are in a separate hierarchy, so no fear of that!

**Comment by aleksisalonen** [comment]
> So full visibility within any organization tree?

Yes, don't see any reason why not. This sort of info is very commonplace in pretty much all such systems I think.

> Well, Espoo is not part of Helsinki at the moment, they are in a separate hierarchy, so no fear of that!

So we have three conditions: part of normal/regular org, admin-user and part of same org hierarchy as target?

**Comment by Rikuoja** [comment]
> > So full visibility within any organization tree?
> 

> So we have three conditions: part of normal/regular org, admin-user and part of same org hierarchy as target?

Yeah, definitely the admin rights should not work across different organization trees.

**Comment by Rikuoja** [comment]
So. Should we display the user who created the event, or the user who last edited it, or both?

And should we allow user name visibility based on the user who created the event, or the user who last edited it?

**Comment by Rikuoja** [comment]
Hm, better base the visibility on the publisher organization, not the original creator's current admin organisation. Though that will lead to some poor ex-employees still being listed and implicated here, even if they no longer are admins in the publisher org, but they will survive.

**Comment by Rikuoja** [comment]
Looks like implementing https://github.com/City-of-Helsinki/linkedevents/issues/325 is running towards a potential combinatorical disaster in the number of required database queries, *if* we are required to check whether the publisher of each listed event is replaced by a new organization in the organization hierarchy. This is because event listings can have lots of events from lots of organizations, and any of them might be replaced by an organization in *any* hierarchy, though in practice they are not.

To avoid having to make a separate database query for each event in the API listing to check whether the user is really allowed to see the creator of each event from each organization *and* their replacements, I suggest that this functionality is limited to non-replaced organizations only.

This would mean that there will be a slight limitation: if the event publisher is a *replaced* organization *outside* the city hierarchy, replaced by an organization in the current hierarchy, the user will not see the creator.

Most likely there are no such organizations, this is just to inform if anybody intends to use this in the future for replacing organizations *across* different hierarchies, since replacements across different hierarchies are theoretically allowed.

**Comment by Rikuoja** [comment]
Also: the event creator will be in `created_by` field, but the backend PR for exposing that field is in the process of being refactored, https://github.com/City-of-Helsinki/linkedevents/issues/325

**Comment by aleksisalonen** [comment]
Ready.
