### ISSUE TITLE
Fix validation error with multiple languages

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#435]
How to reproduce bug:

a) Save event in language 1 only.
b) Edit event, add language 2 to form. 
c) Remove content from (some of) language 1's multilingual fields.
d) Remove language 1 from form (from This event will be presented in following languages. -menu)
e) Save event.

RESULT: Language 1 multilingual fiels data is saved as "null" to API, which should not be allowed. This can result in an event with e.g. a langua 1 description but no language 1 name.

The bug can also result in data being stored (language 1) even though the user wished to remove that data.

Fix validation so that previously held language data (language 1) in multilingual fields is wiped from API completely. The above case should result in an event with language 2 data only.

EDIT: Deselecting all languages on the form is currently allowed. This creates further issues. Change the form's behaviour so that a minimum of one language selection is always required.

**Comment by Rikuoja** [comment]
Deselecting all languages allows you to remove all languages from the event.

Therefore, I wonder, should it be not allowed to uncheck all languages in the form? The form seems to malfunction in such a case.

**Comment by aleksisalonen** [comment]
Yes. Not. Added to issue.
