### ISSUE TITLE
Add fields for video

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#440]
A section for a related video url should be added. 

Section should contain url-field, alt-filed and name field that post to corresponding API-fields.

* Requires new data structure in API, will be done in https://github.com/City-of-Helsinki/linkedevents/issues/349

**Comment by Rikuoja** [comment]
Images have their own endpoint in the API, with metadata such as image size, license, publisher etc: http://api.hel.fi/linkedevents/v1/image/

Should videos have similar data, or do we just want to have an URL field in an event, like `info_url` that already exists in an event?

**Comment by Rikuoja** [comment]
Why do we want `alt_text` for videos but not for images?

**Comment by aleksisalonen** [comment]
I don't think we'll want to start hosting videos. :) That leaves out certain info, like size and makes others like publisher a bit unnecessary perhaps. And I would suppose any licensing issues are sorted out at the hosting send, like Youtube or Helsinkikanava. 

So I think a video in LE should just have I) a name/alt-text and II) an url. 

True, images should have an alt-text or something similar available as well. I think the field "name" can still be used for the alternative image info.

Let's just add the similarily named field "name" for videos for now. On the UI side it can be labeled "Kuvaus eli videon alt-teksti" which would be the new label format for images as well.

**Comment by Rikuoja** [comment]
Okay, the next question is, do we expect the same video to be used in several events, or are the videos specifically for single events? I.e. do we want too keep a list of the linked videos or not?

**Comment by Rikuoja** [comment]
For example, is the video alt text always specific to the event, even if the video is used in several events, or is it specific to the video and not the event?

**Comment by Rikuoja** [comment]
I'm trying to figure out what are the use cases and possible extensions in the future.

**Comment by aleksisalonen** [comment]
The main / first use case is for kulke events and display at kulke websites. Kulke events often have an associated video that is specific to that event.

I think for the kulke use case it's sufficient to store the alt-text on the individual event level (not video-specific).
