### ISSUE TITLE
Change Image tool label for "name"

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#441]
Change the first label in the single image dialog to:

"Kuvaus eli kuvan alt-teksti (korkeintaan 160 merkkiä)"

**Comment by s-arika** [comment]
Could I work on this?

**Comment by Rikuoja** [comment]
@s-arika Go ahead!

**Comment by s-arika** [comment]
@Rikuoja Thanks! Would it be 'Lyhyt kuvaus (korkeintaan 160 merkkiä) (suomeksi) *' label that is being replaced with 'Kuvaus eli kuvan alt-teksti (korkeintaan 160 merkkiä)' ?

**Comment by Rikuoja** [comment]
Nope, I think the right label is "Kuvateksti (korkeintaan 160 merkkiä)", `image-caption-limit` in the translation files.
