### ISSUE TITLE
Add support for posting drafts from regular users

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#445]
The API supports `drafts` as well as published events and `regular` users as well as `admin` users. Currently drafts and regular users aren't supported in the UI, but that should be changed here.

The aim of this issue is to create a workflow and UI views for regular users, who can only post drafts.

We'll use the UI views and workflow for admin-users as a baseline and pare down from that.

1) Regular-users should not be able to publish events. Regular users should only be able to post drafts.
2) Regular users should have the same main views (Event submission etc). as admins.
3) In the Manage events -view, regular users should see a list of their **organizations'** drafts and published events. They should be separated visually with the tags Luonnos/Draft and Julkaistu/Published. Visibility should be based on the user's organization, not individual users.
• Above the window an info text should read: "Julkaistuja tapahtumia ei voi muokata. / Published events can not be edited."
4) Regular users should not be allowed to edit any published events, even from their own organization.
5) The draft posting process should be identical to the admin publishing process, except that at the end, the event should be posted as a draft. 
• The button for posting should read: Lähetä tarkastettavaksi / Send for review
• The new section relating to Umbrella events done in #205 should be hidden from regular users. Hide the section based on user-rights level.
*********
6) A process for dealing with changes after publishing should be put in place. The solution has not been worked out yet

This issue is related to #242 and #284. 

Admin users don't need to post drafts, so the admin workflow should remain unaffected.

**Comment by Rikuoja** [comment]
The API field `publication_status` is used here. Currently, all events are `published`.

So, to create a draft, the UI should set the field to `draft` instead.

**Comment by Rikuoja** [comment]
If the user is not admin, but a regular user instead, the API will provide the list of editable draft events with the filter `/v1/event/?regular_user=uuid`.

Currently, I believe, the UI uses `/v1/event/?admin_user=uuid`.

So the selection between these two should be made depending on if the user has `admin_organizations` or `organization_memberships`, as per https://github.com/City-of-Helsinki/linkedevents-ui/issues/284 .

**Comment by Rikuoja** [comment]
I don't know what we should do if the same user has both admin organizations and regular memberships? Probably not the first issue we encounter.

**Comment by Rikuoja** [comment]
> > So the user may not copy existing event data as basis for their events?
> 
> Yes and just to keep the experience simple.

Okay. They might still just log out and do searching though!
> 
> Is suppose this is a new situation then. I think both should be visible however, so there's transparency for the user and a history of published events.
> 
> I guess there could be a separate window underneath for published events, if that's more sensible API-call-wise. Don't think there's a big difference fo the user, both should be fine.

Yeah, so the question is should we then display
a) only the published events created by the user (`/v1/event/?created_by=uuid`), or
b) all the published events created by the organization the user is a regular member in (`/v1/event/?publisher=publisher_id`) and created the draft for? Or all of them, if the user is a regular member in several organizations?

**Comment by Rikuoja** [comment]
> Admin users don't need to post drafts, so the admin workflow should remain unaffected.

BTW, admin users still probably need a way to distinguish visually between draft and published event. So the DRAFT visual element should always be in the list.

**Comment by aleksisalonen** [comment]
1) Maybe we should hide the Search for all non-admin users. The UI's really not intended as an external event calendar. We have in fact had at least one instance where a city user linked straight to the vent preiview from a public site.
2) Let's give visibility to all drafts from within the same organization. I suppose with visibillity comes also the right to edit drafts from one's fellow members. That's cool here (not for another case along the line I'm thinking of.)
3) Yeah, let's just use publisher id(s). The Manage events view should have a little info box saying only drafts can be edited.
4) > BTW, admin users still probably need a way to distinguish visually between draft and published event. So the DRAFT visual element should always be in the list, regardless of who the user is.

Drafts will only be visible in the moderation panel, put the tags will be good to have there.

**Comment by Rikuoja** [comment]
Looks like the draft badge already exists in the UI code: https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/components/FilterableEventTable/EventRow.js#L72

We just don't have any drafts on the server yet.

**Comment by Rikuoja** [comment]
> 1. Maybe we should hide the Search for all non-admin users. The UI's really not intended as an external event calendar. We have in fact had at least one instance where a city user linked straight to the event preiview from a public site.

Hiding the search doesn't prevent linking to the event preview. Should we hide the event previews too? How about other pages? I would be against it, as the event data is public anyway.

> 2. Let's give visibility to all drafts from within the same organization. I suppose with visibillity comes also the right to edit drafts from one's fellow members. That's cool here (not for another case along the line I'm thinking of.)

Well yeah, the regular user always has draft editing rights anyway. They can just find the events easier if they are listed properly.

**Comment by aleksisalonen** [comment]
Is suppose we could just leave the search visible for all and see if any issues pop up.

**Comment by aleksisalonen** [comment]
This looks to be working as intended!
