### ISSUE TITLE
Fix event end time future check from utc to local timezone

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#446]
Currently, checking whether an event is in the future is off by two or three hours, because https://github.com/City-of-Helsinki/linkedevents-ui/blob/master/src/utils/checkEventEditability.js#L48 compares local times to those in UTC. Both times should be in the same timezone.

**Comment by aleksisalonen** [comment]
Not able to reproduce bug anymore.
