### ISSUE TITLE
Make the nested Umbrella-list refresh properly

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#480]
New or existing events that are added under umbrella events (via #205) are not instantly loaded in the Manage events.

Currently it requires a page refresh to get the nested list to contain new additions.

(This could be very confusing for users.)

**Comment by niglu1** [comment]
I will fix this as part of #242, because I have to refactor the table anyways

**Comment by aleksisalonen** [comment]
Done as part of 242.
