### ISSUE TITLE
Moderation form: Instantly show validation for incomplete event data

### ISSUE THREAD

**Issue by aleksisalonen** [City-of-Helsinki/linkedevents-ui#496]
When a moderator opens a Draft with incomplete data for moderation, the fields with missing data should be instantly marked for easy access.

May be this could be achieved with an extra validation done right at entry to the form.

**Comment by Rikuoja** [comment]
Yeah, this actually ties to https://github.com/City-of-Helsinki/linkedevents-ui/issues/311 , but that issue requires extra code to validate keywords and location too.
