### ISSUE TITLE
The event title field text disappears when updating the event image caption field

### ISSUE THREAD

**Issue by jpaakko** [City-of-Helsinki/linkedevents-ui#537]
The event title field text disappears when updating the event image caption field.

How to reproduce:

1. Click the `Create a new event` button
1. Fill in the event title
1. Click the image upload area to add a new image
1. Click the `Upload image from your hard disk` button
1. Fill in the image caption and move the cursor to another field
1. Close the `Image information` dialog
1. Close the `Event image` dialog
1. Now, the event title field is empty

**Comment by Rikuoja** [comment]
Fixed by #538
