### ISSUE TITLE
Search returns events outside user's organization

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/linkedevents-ui#63]
Search should exclude everything but the user's organization, like "manage events" page does.

**Comment by Rikuoja** [comment]
No it shouldn't. People in an organization may well wish to use external events as templates for their own. The idea is that Manage events page contains the organization events, while the Search page allows you to peruse and copy all events.

**Comment by jussiarpalahti** [comment]
Search is quite barebones at the moment, so getting events outside organization's purview while necessary does complicate finding interesting things. At this point search should either focus on something absolutely necessary or there should be filtering/sorting options to better manage results. And pagination.
