### ISSUE TITLE
Copying to a new event mostly doesn't work.

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#89]
Sometimes, it mysteriously works.

**Comment by jussiarpalahti** [comment]
This ephereal quality for event data probably stems from the fact that its saved in editor state. Trying to copy old event data onto form for new event does not work nor does it touch editor state, thus showing the user old state. By coincidence, this might look like it did the right thing, but when saving the old event would get updated and not new one created.

**Comment by Rikuoja** [comment]
I assume you mean ephemeral?

**Comment by Rikuoja** [comment]
Damn, you were faster.

**Comment by jussiarpalahti** [comment]
I'm ephereal that way...
