### ISSUE TITLE
Missing logout link for nameless users

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#91]

**Comment by aleksisalonen** [comment]
Still missing?

**Comment by Rikuoja** [comment]
https://www.dropbox.com/s/zsrv49nf7f6z270/Screenshot%202019-04-08%2018.39.12.png?dl=0

**Comment by Rikuoja** [comment]
Yes, it is missing. However, not much of an issue since nowadays the users should have a username (from email address if nothing else).

This is caused by old Yle Tunnus users whose username is set empty because Yle didn't provide a username.
