### ISSUE TITLE
YSO autocomplete field doesn't work on IE10

### ISSUE THREAD

**Issue by Rikuoja** [City-of-Helsinki/linkedevents-ui#97]

**Comment by jussiarpalahti** [comment]
Works for me on IE11 and IE10. @juyrjola if you could test further.

**Comment by jussiarpalahti** [comment]
Ping @juyrjola

**Comment by jussiarpalahti** [comment]
Ping @juyrjola, I think this was last (and only) seen on your work laptop...

**Comment by jussiarpalahti** [comment]
OK. Problem has now been seen. IE11 complained about "promise rejection". Couldn't pin point the cause. Shift+reload later and YSO field started working. There is no consistent way to duplicate this nor get IE11 debugger to tell what triggers this error (nor even if it's actually related to this bug at all). 

Leaving this up for now.

**Comment by Rikuoja** [comment]
No further reports of the bug, closing.
